services:
  # FastAPI as the backend/middleware
  backend:
    container_name: backend_knowledge-spaces
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
      x-bake:
        platforms: ["linux/amd64", "linux/arm64"]
    volumes:
      - ./data:/app/data
    ports:
      - 7100:7100

  # SvelteKit as the frontend
  frontend:
    container_name: frontend_knowledge-spaces
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      x-bake:
        platforms: ["linux/amd64", "linux/arm64"]
    ports:
      - 80:80
    depends_on:
      - backend
