services:
  # FastAPI as the backend/middleware
  backend:
    container_name: backend_knowledge-spaces
    image: backend_knowledge-spaces:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
      x-bake:
        platforms: ["linux/amd64", "linux/arm64"]

  # SvelteKit as the frontend
  frontend:
    container_name: frontend_knowledge-spaces
    image: frontend_knowledge-spaces:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      x-bake:
        platforms: ["linux/amd64", "linux/arm64"]
