version: "3.8"

services:
  # FastAPI as the backend/middleware
  backend:
    container_name: backend_knowledge-spaces
    image: francescosch/backend_knowledge-spaces:latest
    ports:
      - "7100:7100"
    volumes:
      - ./data:/data
    networks:
      - default_knowledge-spaces

  # SvelteKit as the frontend
  frontend:
    container_name: frontend_knowledge-spaces
    image: francescosch/frontend_knowledge-spaces:latest
    depends_on:
      - backend
    ports:
      - "80:3000"
    environment:
      - PUBLIC_BACKEND_URL=http://localhost:7100
    networks:
      - default_knowledge-spaces

networks:
  default_knowledge-spaces:
    name: knowledge-spaces
