version: "3.8"

services:
  # FastAPI as the backend/middleware
  backend:
    container_name: backend_knowledge-spaces
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend/src:/app
    # The ports are exposed for easier development and debugging
    ports:
      - 7100:7100

  # SvelteKit as the frontend
  frontend:
    container_name: frontend_knowledge-spaces
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8080
    environment:
      - PUBLIC_BACKEND_URL=http://backend:7100
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    depends_on:
      - backend
