version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - 7100:7100
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 7100

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./frontend/:/app/
  #     # - /usr/src/app/node_modules
