services:
  # Qdrant as the database
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - ./qdrant/storage:/qdrant/storage

  # FastAPI as the backend/middleware
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    depends_on:
      - qdrant

  # SvelteKit as the frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - 80:80
    depends_on:
      - backend
