services:
  # Qdrant as the database for embeddings
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - ./qdrant/storage:/qdrant/storage

  # FastAPI as the backend
  backend:
    build: ./backend
    ports:
      - 7100:7100
    volumes:
      - ./backend:/app
    depends_on:
      - qdrant

  # SvelteKit as the frontend
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./frontend/:/app/
  #     # - /usr/src/app/node_modules
